### PR TITLE
Removing unused Environment.StackTrace and getting UserDomainName and UserName in constructor

### LINKED ISSUE #12: Remove unused Environment.StackTrace code
There is a line in InternalWrite that calls Environment.StackTrace.

This is no longer used and may cause a performance hit.  It should be removed.

### PR DESCRIPTION
**Pull request by bstauff**
Removed unused Environment.StackTrace.  Closes #12 #14

### CODE REVIEW

File: ElasticSearch.Diagnostics/ElasticSearchTraceListener.cs [hunk 1]
```diff
@@ -349,10 +349,10 @@ private void SetupObserverBatchy()
                         {"TraceId", traceId ?? 0},
                         {"EventType", eventType.ToString()},
                         {"UtcDateTime", logTime},
-                        {"timestamp", eventCache != null ? eventCache.Timestamp : 0},
+                        {"timestamp", eventCache?.Timestamp ?? 0},
```
Comment (amccool) [inline ElasticSearch.Diagnostics/ElasticSearchTraceListener.cs]: language features necessary?

**Comment by amccool** [comment]
Thanks @bstauff !! 🥇 💯
